---
name: release

on:
  release:
    types:
      - created

jobs:
  release-launcher-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set release version
        run: |
          RELEASE_TAG=${{ github.ref_name }}
          RELEASE_VERSION=${RELEASE_TAG#v}

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_ENV"

      - name: set netopeer image to match launcher image
        run: |
          sed -i "s|\(image: ghcr.io/scrapli/scrapli_clab/netopeer:\).*|\1${{ env.RELEASE_VERSION }}|" launcher/topos/topo.amd64.yaml
          cat launcher/topos/topo.amd64.yaml | grep netopeer
          sed -i "s|\(image: ghcr.io/scrapli/scrapli_clab/netopeer:\).*|\1${{ env.RELEASE_VERSION }}|" launcher/topos/topo.arm64.yaml
          cat launcher/topos/topo.arm64.yaml | grep netopeer
          sed -i "s|\(image: ghcr.io/scrapli/scrapli_clab/netopeer:\).*|\1${{ env.RELEASE_VERSION }}|" launcher/topos/topo.ci.amd64.yaml
          cat launcher/topos/topo.ci.amd64.yaml | grep netopeer

      - name: enable containerd image store
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: qemu for emulation support
        uses: docker/setup-qemu-action@v3

      - name: build and push launcher image
        uses: docker/build-push-action@v6
        with:
          context: launcher
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/scrapli/scrapli_clab/launcher:${{ env.RELEASE_VERSION }}
            ghcr.io/scrapli/scrapli_clab/launcher:latest

  release-netopeer-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set release version
        run: |
          RELEASE_TAG=${{ github.ref_name }}
          RELEASE_VERSION=${RELEASE_TAG#v}

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_ENV"

      - name: enable containerd image store
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: qemu for emulation support
        uses: docker/setup-qemu-action@v3

      - name: build and push netopeer image
        uses: docker/build-push-action@v6
        with:
          context: netopeer
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/scrapli/scrapli_clab/netopeer:${{ env.RELEASE_VERSION }}
            ghcr.io/scrapli/scrapli_clab/netopeer:latest

  release-jumper-image:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: login to ghcr
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set release version
        run: |
          RELEASE_TAG=${{ github.ref_name }}
          RELEASE_VERSION=${RELEASE_TAG#v}

          echo "RELEASE_VERSION=$RELEASE_VERSION" >> "$GITHUB_ENV"

      - name: enable containerd image store
        uses: docker/setup-docker-action@v4
        with:
          daemon-config: |
            {
              "debug": true,
              "features": {
                "containerd-snapshotter": true
              }
            }

      - name: qemu for emulation support
        uses: docker/setup-qemu-action@v3

      - name: build and push jumper image
        uses: docker/build-push-action@v6
        with:
          context: jumper
          push: true
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/scrapli/scrapli_clab/jumper:${{ env.RELEASE_VERSION }}
            ghcr.io/scrapli/scrapli_clab/jumper:latest
